apiVersion: v1
kind: Service
metadata:
    name: argo-nodeport
    namespace: argocd
spec:
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    targetPort: 8080
    resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
