apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: demo
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            anonymous-auth: "false"
            authentication-token-webhook: "true"
            authorization-mode: "Webhook"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            anonymous-auth: "false"
            enable-admission-plugins: "NodeRestriction,PodSecurityPolicy"
            audit-log-path: "/var/log/kubernetes/audit.log"
            audit-log-maxage: "30"
            audit-log-maxbackup: "10"
            audit-log-maxsize: "100"
    extraPortMappings:
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
