name: Secret Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: brenesrm
  IMAGE_NAME: devsecops-nyit-van

jobs:
  check-secrets:
    name: Secrets Management Analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Detect Secrets
        run: pip install detect-secrets  # Ensure detect-secrets is installed

      - name: Generate Secrets Baseline (if missing)
        run: |
          if [ ! -f ".secrets.baseline" ]; then
            detect-secrets scan > .secrets.baseline
          fi

      - name: Secret Scanner
        run: detect-secrets scan --baseline .secrets.baseline || true  # Allow process to continue

      - name: Check and Upload Secrets Report
        run: |
          if [ -f ".secrets.baseline" ]; then
            echo "Secrets baseline file found. Uploading..."
          else
            echo "No secrets baseline file found! Exiting..."
            exit 1
          fi

      - name: Save Secrets Report
        uses: actions/upload-artifact@v4
        with:
          name: secrets-scan-report
          path: .secrets.baseline
          retention-days: 30
