apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-nyit-van
  labels:
    app: devsecops-nyit-van
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-nyit-van
  template:
    metadata:
      labels:
        app: devsecops-nyit-van
    spec:
      containers:
      - name: devsecops-nyit-van
        image: brenesrm/devsecops-nyit-van:latest
        ports:
        - containerPort: 5000
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-nyit-van-service
spec:
  type: NodePort
  selector:
    app: devsecops-nyit-van
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 80