name: PIPELINE-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# This part is intentional and needs to be scanned for exposed secrets.
env:
  DOCKER_REGISTRY: brenesrm
  IMAGE_NAME: devsecops-nyit-van
  PASSWORD: "PuraVida!"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04

    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push the Docker image
      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

      # 4. Verify Docker image exists
      - name: Verify Docker image
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  dast:
    name: ZAP - DAST Test
    runs-on: ubuntu-latest
    permissions:
      issues: write
      security-events: write
      actions: write  # Needed for artifact upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          python app.py &
          for i in {1..15}; do
            if curl -sSf http://localhost:5000 >/dev/null; then
              echo "Flask app is running!"
              exit 0
            fi
            sleep 2
          done
          echo "Flask app failed to start"
          exit 1

      - name: Run ZAP Full Scan  # More comprehensive than baseline
        uses: zaproxy/action-full-scan@v0.10.0  # Updated to latest version
        with:
          target: 'http://localhost:5000'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'ZAP Security Scan Findings'
          container: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-I'  # Ignore warning rules
          
      - name: Upload Scan Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-results  # Hyphens instead of underscores
          path: |
            report_json.json
            report_md.md
            report_html.html      
      
    
