name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: brenesrm
  IMAGE_NAME: devsecops-nyit-van

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & Push the Docker image
      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

      # 4. Verify Docker image exists
      - name: Verify Docker image
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # 5. Log build activities
      - name: Log build to file
        if: always()
        run: |
          echo "Workflow: ${{ github.workflow }}" >> build_audit.log
          echo "Branch: ${{ github.ref }}" >> build_audit.log
          echo "Commit: ${{ github.sha }}" >> build_audit.log
          echo "Status: ${{ job.status }}" >> build_audit.log

      # 6. Upload audit log as an artifact
      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-audit-log
          path: build_audit.log

#----------------------------------------------------------

  dockertest:
    name: Run Docker tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1. scan Docker image
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
